### ISSUE TITLE
Calibrating Lux to be in line with SL01

### ISSUE THREAD

**Issue by PragmaticPhil** [xinabox/pxt-SL06#2]
There are 3 issues this ticket will address:

1 - The lux values being reported on the SL06 are way too high
2 - the lux values being reporting on the SL06 are way out of kilter with the values from the SL01.
3 - the functions in SL06 and SL01 return the exact same value - they should be exactly the same: name and input parameters, and when side by side should return similar values (see image)

![SL01_Sl06](https://user-images.githubusercontent.com/10323597/77081745-003a1f80-69f3-11ea-9e7d-c90ed4a9aafd.png)

Note - in image above the values were recorded when a strong torch was shone onto the sensors - it was shone on both at the same time.  This pattern of results (SL06 much higher than SL01) is consistent.  SL01 readings conform much more with expectations for lux.

Please:
... calibrate SL06 in line with SL01
... rename function in SL06 so it is in line with SL01.

NB - there is a lot of documentation about SL01 so please no changes there.

**Comment by KalbeAbbas** [comment]
Thanks. It needed gain adjustment. Ambient light sensing had 4X gain. Its Ok now.

**Comment by PragmaticPhil** [comment]
Thanks.  Please update the function name in line with SL01 then let me know (on Slack) when its done

**Comment by gotfredsen** [comment]
@pm, please close this when ok.

**Comment by PragmaticPhil** [comment]
The anomalies are still apparent - less so than before.
BUT - in a side by side comparison of SL01 and SL06 the difference between the results is large enough that one of them is 'wrong'.

NOTE - based on my previous observations of lux at my desk, the SL01 gives a result that feels more 'right'.  SL06 is reporting values below SL01.

I am using this code to test:
https://makecode.microbit.org/_KeFhCoE96Ukq

See attached image for more context:

![Picture1](https://user-images.githubusercontent.com/10323597/77339663-08ac9600-6d24-11ea-9e0a-9c7764aecfa1.png)

**Comment by KalbeAbbas** [comment]
Did you update the library? I am getting results which are comparable.|

![image](https://user-images.githubusercontent.com/49709412/77395083-9f2f9480-6dc2-11ea-8d5e-740e3a106bc9.png)

(Screenshot is from makecode console)

**Comment by PragmaticPhil** [comment]
Library was updated. Results are replicable here

The example KJ has pasted above shows a discrepancy of close to 20percent. 
At lower levels (<100) I am getting about 10percent
At higher light levels the discrepancy rises 

@gotfredsen - please can you make a call on whether this is an acceptable "margin of error".  
I would prefer a max discrepancy of 10percent across the board, but I realise this might be unrealistic - I am not sure what we should 'settle' for

**Comment by gotfredsen** [comment]
So not all sensors are the same. In general all sensors are some kind of analog solution that either gives this uncalibrated output or it is being translated to a digital output using a builtin ADC (analog-digital-converter). That can give 3 results:

1. The raw digital output, say it is a 10bit ADC, that gives 1024 different values (0-1023). The output will just be a number in that range.
2. The digital number is being internally calibrated and you are giving a formula how to interpret the output. Once you have done this interpretation, you will have an accurate read in a specific unit.
3. You will get the raw digital output and the sensor manufacture have then loaded a calibration value into a register. You are given a much longer formula to read the raw digital data, read the calibration registers merge the two the correct way, and you now have an accurate output with a specific unit. This 3rd way is the most used way for instrumentation level sensors, since the manufacture can make the sensor, send it through a calibrated environment and then load the discrepancies into the calibration registers, without otherwise changing the component.

The SL01 is such sensor with a calibrated output used to give you an accurate reading for instrument usage. The SL06 does not offer a calibrated output. What that means is that with a number of SL01 correctly programmed output, you should get a value of accuracy within the announce precision indicated in the data sheet. The same you cannot expect from the SL06. The ambient light sensor on the SL01, the TSL4531, can only measure ambient light level, aka Lux, nothing else, it is its purpose. The SL06 on the other hand can measure lots of different stuff. And the sensor price for the SL06 is considerably lower than the SL01.

So why is there a sensor like the SL06 if it is not accurate and why do we offer it?
Well first of all, the lower price allows us to produce an xChip for a lower price, with lot of functionality allowing entry level users a cheaper peep into this world. And while the lux reading might not be accurate, the gesture part works fine.
A sensor like this exist not for us, but for smart phones and similar electronics. It is not being used to measure accurate lux or colour levels, but just accurate enough that the smart phone maker can adjust the display brightness and colour temperature.

**I suggest we leave the reading as it is**, and make sure we somehow indicate that the lux levels on the SL01 is more accurate than on the SL06. This will also be the case with lots of other sensors, such as humidity sensors. Each user has to figure out which sensor he believes will do the right job. Take a look at this research http://www.kandrsmith.org/RJS/Misc/Hygrometers/calib_many.html - it concludes that our SW01 is best, not that we have made xChips with all the other sensors, but we could have to give uses a lower priced entry option, like what we have done with the SL06.

**Comment by PragmaticPhil** [comment]
Thanks... suggestion is fine with me... key is being able to document (or in the first instance understand) any discrepancies... and so I can use SL06 to its strengths. 
And it is reassuring SL01 is accurate.

Shall we add a Calibrate block to the SL06?  Pass in an integer (percentage weight - easier for inexperienced users than a coefficient) - return weighted value?
... PS - I don't think I feel strongly about this: just think its an intriguing option.
However this question ends up I will close the ticket.

**Comment by gotfredsen** [comment]
Let's leave it out of MakeCode, which is not for advanced users anyhow, but, yes, an intriguing option.
