### ISSUE TITLE
Gesture sensing on SL06

### ISSUE THREAD

**Issue by PragmaticPhil** [xinabox/pxt-SL06#4]
Please enable gesture sensing blocks for micro:bit

**Comment by PragmaticPhil** [comment]
@gotfredsen how do you feel about making it easier for the users by providing them with obvious blocks (in addition to the existing ones):

Gesture is Up
Gesture is Down
Gesture is Right
Gesture is Left
(each returns a boolean)

Note - I am assuming that when gesture mode is on, the most recent valid gesture is 'cached' somehow, and any call to the SL06 to get gesture returns the gesture in the cache?  Also that the cached is not reset when its queried?  Is this right?
If so how is a gesture replaced with 'no gesture'?

**Comment by KalbeAbbas** [comment]
@PragmaticPhil The gesture sensing in SL06 doesn't work like that. The output gives **none** when no gesture is received, otherwise returns valid gesture.

**Comment by gotfredsen** [comment]
@KalbeAbbas you can make an "on gesture <direction>"  callback function, and then just do continuous polls of the SL06.

In any case the SL06 has an interrupt output (if soldered), it uses the PROG pin we now call Alert. It is currently only a solder pads, because it will confuse the CW01/CW02 if used with those. But if used with CC03/CS11/CW03 alone then it should work with the Alert pin. @KalbeAbbas if you haven't included that pin in your CS11/CC03 definition, maybe do so now and call it Alert
Pins:

- CS11: PA07
- MicroBit: Button B
- CC03: pls ask @brendanvanbreda 
- CW03: PA18

...but for the above library and for now, I don't suggest using the interrupt, just constant polling.

**Comment by PragmaticPhil** [comment]
Thanks.  
Forgive my non-technical level of understanding, and I am sure you all have this covered (its probs bread and butter stuff)...

With constant polling - I don't understand the periodicity of this - how long a poll event takes and how that overlaps with timing on the forever loop.  Do we know for sure that a not-None value will always persist for the duration of a forever cycle and will be set to that not-None value for the whole cycle?  Could we get 2 different values in the same forever loop (I think we shouldn't - esp if we are polling in if statements)?

 wrt a boolean block called Gesture is Up
... I am just suggesting that we output the bool: [_value = Up_] - we're outputting value anyway, and this means that our end users don't have to spend time working out which return value corresponds to each direction, which they have to now and which they won't thank us for ;)

**Comment by gotfredsen** [comment]
@KalbeAbbas has to work on this to see if it possible. Depending on the implementation of TypeScript/MakeCode then a delay can either be waiting at the spot, or it can be do a lot of stuff, but checking a timer says the correct time has gone by.  In Arduino we would not use a delay-function because nothing else would then happen, but we let the loop continuous run and check if the right time has gone by, while the loop is running we will then continuous check if a sensor has new info such as gestures from SL06.
Let's see what @KalbeAbbas comes back with, then we can look at the cosmetics.

**Comment by PragmaticPhil** [comment]
The gesture reporting now works :)

There are significant usability / 'cosmetic' issues - the average microbit user will struggle to use this properly in MakeCode.

I will close this ticket and start a new one with usability issues
